apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-api-config
  namespace: {{NAMESPACE}}
  labels:
    app: spring-boot-api
    component: backend
    environment: {{NAMESPACE}}
data:
  # Application configuration
  application.yml: |
    server:
      port: 8080
      servlet:
        context-path: /
      compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 1024
      
    spring:
      application:
        name: spring-boot-api
      datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password: password
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          ddl-auto: update
        show-sql: false
        properties:
          hibernate:
            format_sql: true
      h2:
        console:
          enabled: false
      
    management:
      server:
        port: 8081
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
          base-path: /actuator
      endpoint:
        health:
          show-details: always
          show-components: always
          probes:
            enabled: true
        metrics:
          enabled: true
        prometheus:
          enabled: true
      health:
        livenessstate:
          enabled: true
        readinessstate:
          enabled: true
        db:
          enabled: true
      metrics:
        export:
          prometheus:
            enabled: true
    
    logging:
      level:
        com.techassessment: INFO
        org.springframework.web: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      file:
        name: /app/logs/spring-boot-api.log
        max-size: 10MB
        max-history: 30
  
  # Environment-specific overrides
  application-development.yml: |
    logging:
      level:
        com.techassessment: DEBUG
        root: DEBUG
    spring:
      h2:
        console:
          enabled: true
    management:
      endpoints:
        web:
          exposure:
            include: "*"
  
  application-staging.yml: |
    logging:
      level:
        com.techassessment: DEBUG
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
  
  application-production.yml: |
    logging:
      level:
        com.techassessment: WARN
        root: WARN
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-api-secrets
  namespace: {{NAMESPACE}}
  labels:
    app: spring-boot-api
    component: backend
    environment: {{NAMESPACE}}
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  database-password: cGFzc3dvcmQ=  # password
  jwt-secret: bXktand0LXNlY3JldC1rZXk=  # my-jwt-secret-key
  api-key: bXktYXBpLWtleQ==  # my-api-key 